before_script:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y
    biblatex
    latexmk
    texlive
    texlive-base
    texlive-latex-extra
    texlive-latex-recommended
    texlive-pictures
    texlive-science
  - git clone git@github.com:plk/biber.git
  - export PATH=$PATH:$(pwd)/biber/bin
script:
  - cd diplomarbeit
  - latexmk -pdf -interaction=nonstopmode -file-line-error -shell-escape diplomarbeit
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
