language: cpp
compiler: gcc
before_script: sudo ./tools/setup.sh
script: ./bootstrap.sh && ./configure && make check
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
