language: cpp
compiler:
  - gcc
  - clang
before_script: ./travis-deps.sh
script: make
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
