language: cpp
compiler: gcc
before_script: sudo apt-get install -qq -y libboost-all-dev libboost-dbg ; sudo setup-ubigraph.sh
script: make
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
