language: cpp
compiler: gcc
before_script: sudo ./tools/setup.sh
script:
  - aclocal
  - automake --gnu --add-missing
  - autoconf
  - ./configure
  - make check
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
