language: cpp
compiler: clang
before_script:
  - sudo apt-get install -qq libboost-all-dev libboost-dbg automake autoconf-archive gnulib libcppunit-dev freeglut3 libxmlrpc-c3-dev valgrind cppcheck
  - sudo ./tools/setup-ubigraph.sh
script:
  - cppcheck --quiet --verbose --enable=all --error-exitcode=1 .
  - aclocal
  - automake --gnu --add-missing
  - autoconf
  - ./configure
  - make check
  - make
  - valgrind --error-exitcode=1 --leak-check=full --track-origins=yes --show-reachable=yes -v ./src/pcp-vns -n cnd -d 4 < ./tests/instance.pcp
notifications:
  email:
    recipients:
      - lorenz.leutgeb@gmail.com
    on_success: never
    on_failure: change
